import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Common/Navbar";
import { ThemeProvider } from "next-themes";

const funnelSans = Funnel_Sans({
	variable: "--font-funnel-sans",
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${funnelSans.className} antialiased`}
				suppressHydrationWarning
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange={false}
					storageKey="theme"
				>
					<Navbar />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
